apiVersion: v1
kind: Service
metadata:
  name: ms-aggregator-cache
  labels:
    app: ms-aggregator-cache
spec:
  selector:
    app: ms-aggregator-cache
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
