apiVersion: v1
kind: Service
metadata:
  name: ms-search-aggregator
spec:
  selector:
    app: ms-search-aggregator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP