apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user
  labels:
    app: ms-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-user
  template:
    metadata:
      labels:
        app: ms-user
    spec:
      containers:
        - name: ms-user
          image: yenyinglu/ms-user-service:placeholder
          ports:
            - containerPort: 8000
